### ISSUE TITLE
call  evmc_load crash

### ISSUE THREAD

**Issue by fpcfjf** [ewasm/hera#548] opened 2019-07-12 04:12 UTC
hera\evmc\lib\loader:（Windows）
evmc_create_fn evmc_load(const char* filename, enum evmc_loader_error_code* error_code)

input:
char *p = (char*)100;//cause crash
enum evmc_loader_error_code* ec;
evmc_load(p,ec);//crash

The reason is that:
evmc_create_fn evmc_load(const char* filename, enum evmc_loader_error_code* error_code)
{
    last_error_msg = NULL;  // Reset last error.
    enum evmc_loader_error_code ec = EVMC_LOADER_SUCCESS;
    evmc_create_fn create_fn = NULL;

    if (!filename)
    {
        ec = set_error(EVMC_LOADER_INVALID_ARGUMENT, "invalid argument: file name cannot be null");
        goto exit;
    }

    const size_t length = strlen(filename);//cause---------this

**Comment by axic** [comment] 2019-07-15 00:49
How do you expect a C API could detect an invalid non-null pointer?

Also this is not specific to Hera, but https://github.com/ethereum/evmc.

I'm closing this because it is not a bug.

**Closed by axic** 2019-07-15 00:49 UTC

**Comment by fpcfjf** [comment] 2019-07-17 03:02
thanks,i think so
