### ISSUE TITLE
Hera fails to execute AssemblyScript WAST

### ISSUE THREAD

**Issue by lrettig** [ewasm/hera#258] opened 2018-06-26 17:34 UTC
I'm getting the following error running a test that includes valid WAST that's generated from AssemblyScript:

```
> cpp-ethereum/build/test/testeth -t GeneralStateTests/stEWASMTests -- --testpath tests/ --singlenet Byzantium --jsontrace '' --vm hera/build/src/libhera.dylib --filltests --singletest wrc20Challenge
Running tests using path: "tests/"
Running 1 test case...
Test Case "stEWASMTests":
100%
cpp-ethereum/test/tools/libtesteth/wast2wasm.cpp:38: error: in "GeneralStateTests/stEWASMTests": Error parsing wasm: [parse exception: expected list (at 1:804)]
Executing...
importGlobals
$call 186a0 80 120 0 18
Executing...
Contract entry point ("main") missing.
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<dev::eth::InternalVMError>: cpp-ethereum/libevm/EVMC.cpp(76): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256 &, dev::eth::ExtVMFace &, const dev::eth::OnOpFunc &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = 13

unknown location:0: fatal error: in "GeneralStateTests/stEWASMTests": signal: SIGABRT (application abort requested)
cpp-ethereum/test/tools/libtesteth/wast2wasm.cpp:41: last checkpoint

*** 2 failures are detected (5 failures are expected) in the test module "Master Test Suite"
```

Here's the WAST in question:
```
(module
  (type $t0 (func))
  (type $t1 (func (result i32)))
  (type $t2 (func (param i32 i32)))
  (type $t3 (func (param i32) (result i32)))
  (type $t4 (func (param i32 i32 i32)))
  (import "ethereum" "getCallDataSize" (func $main/ethereum_getCallDataSize (type $t1)))
  (import "ethereum" "revert" (func $main/ethereum_revert (type $t2)))
  (import "ethereum" "callDataCopy" (func $main/ethereum_callDataCopy (type $t4)))
  (import "ethereum" "storageLoad" (func $main/ethereum_storageLoad (type $t2)))
  (import "ethereum" "return" (func $main/ethereum_return (type $t2)))
  (import "debug" "printMemHex" (func $printMemHex (param i32 i32)))
  (func $~lib/allocator/arena/allocate_memory (type $t3) (param $p0 i32) (result i32)
    (local $l0 i32) (local $l1 i32) (local $l2 i32) (local $l3 i32) (local $l4 i32) (local $l5 i32)
    get_local $p0
    if $I0
      get_local $p0
      i32.const 1073741824
      i32.gt_u
      if $I1
        unreachable
      end
      get_global $g5
      set_local $l0
      get_local $l0
      get_local $p0
      i32.add
      i32.const 7
      i32.add
      i32.const 7
      i32.const -1
      i32.xor
      i32.and
      set_local $l1
      current_memory
      set_local $l2
      get_local $l1
      get_local $l2
      i32.const 16
      i32.shl
      i32.gt_u
      if $I2
        get_local $l1
        get_local $l0
        i32.sub
        i32.const 65535
        i32.add
        i32.const 65535
        i32.const -1
        i32.xor
        i32.and
        i32.const 16
        i32.shr_u
        set_local $l3
        get_local $l2
        tee_local $l4
        get_local $l3
        tee_local $l5
        get_local $l4
        get_local $l5
        i32.gt_s
        select
        set_local $l4
        get_local $l4
        grow_memory
        i32.const 0
        i32.lt_s
        if $I3
          get_local $l3
          grow_memory
          i32.const 0
          i32.lt_s
          if $I4
            unreachable
          end
        end
      end
      get_local $l1
      set_global $g5
      get_local $l0
      return
    end
    i32.const 0)
  (func $main/do_balance (type $t0)
    (local $l0 i32) (local $l1 i32) (local $l2 i32)
    call $main/ethereum_getCallDataSize
    i32.const 24
    i32.ne
    if $I0
      i32.const 0
      i32.const 0
      call $main/ethereum_revert
    end
    i32.const 32
    call $~lib/allocator/arena/allocate_memory
    set_local $l0
    get_local $l0
    i32.const 4
    i32.const 20
    call $main/ethereum_callDataCopy
    get_local $l0
    i32.load
    set_local $l1
    i32.const 32
    call $~lib/allocator/arena/allocate_memory
    set_local $l2
    get_local $l0
    i32.const 32
    call $printMemHex
    get_local $l1
    get_local $l2
    call $main/ethereum_storageLoad
    get_local $l2
    i32.const 32
    call $main/ethereum_return)
  (func $main/do_transfer (type $t0)
    nop)
  (func $main/main (export "main") (type $t0)
    (local $l0 i32) (local $l1 i32) (local $l2 i32)
    call $main/ethereum_getCallDataSize
    i32.const 4
    i32.lt_s
    if $I0
      i32.const 0
      i32.const 0
      call $main/ethereum_revert
    end
    i32.const 4
    call $~lib/allocator/arena/allocate_memory
    set_local $l0
    get_local $l0
    i32.const 0
    i32.const 4
    call $main/ethereum_callDataCopy
    get_local $l0
    i32.load
    set_local $l1
    get_local $l0
    i32.const 32
    call $printMemHex
    block $B1
      block $B2
        block $B3
          block $B4
            get_local $l1
            set_local $l2
            get_local $l2
            i32.const -1718418918
            i32.eq
            br_if $B4
            get_local $l2
            i32.const 1563795389
            i32.eq
            br_if $B3
            br $B2
          end
          call $main/do_balance
          br $B1
        end
        call $main/do_transfer
        br $B1
      end
      i32.const 0
      i32.const 0
      call $main/ethereum_revert
    end)
  (func $start (type $t0)
    get_global $g6
    i32.const 7
    i32.add
    i32.const 7
    i32.const -1
    i32.xor
    i32.and
    set_global $g4
    get_global $g4
    set_global $g5)
  (memory $memory (export "memory") 1)
  (global $g0 i32 (i32.const 3))
  (global $g1 i32 (i32.const 8))
  (global $g2 i32 (i32.const 7))
  (global $g3 i32 (i32.const 1073741824))
  (global $g4 (mut i32) (i32.const 0))
  (global $g5 (mut i32) (i32.const 0))
  (global $g6 i32 (i32.const 8))
  (start 9))
```

**Comment by axic** [comment] 2018-06-26 17:49
Since Hera can only execute wasm (binary), can you post the binary instead? (in base64 or something)

> Contract entry point ("main") missing.

The message means it couldn't identify a proper `main` function.

Also it seems that it has a `start` method, which it shouldn't.

**Comment by lrettig** [comment] 2018-06-27 01:44
> The message means it couldn't identify a proper main function.

There is a main function. I played around with naming, removing the $type, etc. and that didn't seem to make a difference.

> Also it seems that it has a start method, which it shouldn't.

What do you mean by "it shouldn't"? I'm not sure what's adding this--I wonder if it has to do with the memory management module.

Here's the WASM in base64:

AGFzbQEAAAABGAVgAABgAAF/YAJ/fwBgAX8Bf2ADf39/AAKDAQYIZXRoZXJldW0P
Z2V0Q2FsbERhdGFTaXplAAEIZXRoZXJldW0GcmV2ZXJ0AAIIZXRoZXJldW0MY2Fs
bERhdGFDb3B5AAQIZXRoZXJldW0Lc3RvcmFnZUxvYWQAAghldGhlcmV1bQZyZXR1
cm4AAgVkZWJ1ZwtwcmludE1lbUhleAACAwYFAwAAAAAFAwEAAQYoB38AQQMLfwBB
CAt/AEEHC38AQYCAgIAEC38BQQALfwFBAAt/AEEICwcRAgRtYWluAAkGbWVtb3J5
AgAIAQkKvAIFfgEGfyAABEAgAEGAgICABEsEQAALIwUhASABIABqQQdqQQdBf3Nx
IQI/ACEDIAIgA0EQdEsEQCACIAFrQf//A2pB//8DQX9zcUEQdiEEIAMiBSAEIgYg
BSAGShshBSAFQABBAEgEQCAEQABBAEgEQAALCwsgAiQFIAEPC0EACz8BA38QAEEY
RwRAQQBBABABC0EgEAYhACAAQQRBFBACIAAoAgAhAUEgEAYhAiAAQSAQBSABIAIQ
AyACQSAQBAsDAAELYwEDfxAAQQRIBEBBAEEAEAELQQQQBiEAIABBAEEEEAIgACgC
ACEBIABBIBAFAkACQAJAAkAgASECIAJBmoTMzHlGDQAgAkG9v9bpBUYNAQwCCxAH
DAILEAgMAQtBAEEAEAELCxMAIwZBB2pBB0F/c3EkBCMEJAUL

**Comment by jwasinger** [comment] 2018-06-27 05:41
Looks like your wast declares the function "main/main" and then exports "main".

It would be easier to reproduce this if you posted wast that follows the s-expression format.

**Comment by lrettig** [comment] 2018-06-27 11:55
The WAST compiles fine using wabt's wat2wasm. Also this isn't "my wast," this is valid wast being produced by the AssemblyScript compiler -- which *cough* is built on binaryen. Doesn't make sense.

**Comment by MaxGraey** [comment] 2018-06-27 12:05
Hi, @lrettig. This wasm was generated as result from [this demo](https://github.com/lrettig/ewasm-assemblyscript-demo)?

**Comment by axic** [comment] 2018-06-27 12:12
> Looks like your wast declares the function "main/main" and then exports "main".

That shouldn't make any difference, `$main/main` is the internal symbol in the wast, not even present in the wasm.

> What do you mean by "it shouldn't"?

The "ECI" states that we do not support the start flag :)

**Comment by MaxGraey** [comment] 2018-06-27 12:29
I guess the error with missing `main` may be appear with wrong function signature.
You use:
```ts
export function main(): void {
  ...
}
```
instead `int main(int argc, char* argv[])` which in AS equivalent to:
```ts
export function main(argc: i32, char: usize): i32 {
   ...
}
```

**Comment by MaxGraey** [comment] 2018-06-27 12:35
@axic 
> The "ECI" states that we do not support the start flag :)
 
You mean you don't support `start` entry point provided by WebAssembly design?

**Comment by MaxGraey** [comment] 2018-06-27 12:46
@lrettig 
> What do you mean by "it shouldn't"? I'm not sure what's adding this--I wonder if it has to do with the memory management module.

Definitely you are right. Init code for mem management put into `start` entry point.

**Comment by lrettig** [comment] 2018-06-27 13:18
>> What do you mean by "it shouldn't"?

> The "ECI" states that we do not support the start flag :)

Where?

**Comment by dcodeIO** [comment] 2018-06-27 17:56
FYI: asc now omits the `start` entrypoint if an exported `main` function is present and instead prepends a call to start to the main function's body ([commit](https://github.com/AssemblyScript/assemblyscript/commit/27e61f8f679607503c232c31f251a1cbd6321462)).

**Comment by lrettig** [comment] 2018-06-27 18:00
Thanks @dcodeIO this is helpful to know

**Comment by axic** [comment] 2018-06-27 20:59
> I guess the error with missing main may be appear with wrong function signature.

@MaxGraey actually we have decided to have `main()` as the function signature. Would that be an incompatibility with AssemblyScript?

> You mean you don't support start entry point provided by WebAssembly design?

Yes, but this restriction came around the time of wasm version 0xb, we may need to revisit VMs to clarify whether the reasons for disabling it are still valid.

> FYI: asc now omits the start entrypoint if an exported main function is present and instead prepends a call to start to the main function's body (commit).

@dcodeIO nice! I briefly had a look at the patch. Did I get it right that it only checks for the presence of an export with the name of "main" irrelevant of the type? e.g. `main()` would still be counted as "main" ?

**Comment by MaxGraey** [comment] 2018-06-27 21:19
> actually we have decided to have main() as the function signature. Would that be an incompatibility with AssemblyScript?

For AS this is absolutely not important, I thought this is important for your VM and infrastructure that is trying to pass parameters that are not supported. I was guided this C++ [contract example from evmc](https://github.com/ethereum/evmc/blob/cb2288b49d460d388831e45ba310e43ad2e3bf06/examples/capi.c#L133) and guess this may be some metter.

**Comment by dcodeIO** [comment] 2018-06-27 21:40
> Did I get it right that it only checks for the presence of an export with the name of "main" irrelevant of the type? e.g. main() would still be counted as "main" ?

@axic Yes, if it finds a non-generic, non-ambient function export using the external name "main", it assumes that's the main function (regardless of its parameters) and skips generating the `(start ...)` entrypoint.

There is also [a way to inject custom transforms](https://github.com/AssemblyScript/assemblyscript/issues/20) into the compilation process. So if you guys would like to implement additional validation of this feature, you could inject a `--transform ethereum/check.ts` that runs the necessary checks on the AST prior to compiling anything.

**Comment by axic** [comment] 2018-06-27 21:59
Thank you @MaxGraey and @dcodeIO again for the insanely quick turnaround of answers 👍

I (and I think others agree with me) would be really interested in having AssemblyScript as one of the first well supported languages for ewasm, though we're still very early in the process.

One thing which would make life super convenient is having access to wasm's namespaces when importing external functions. Do you have that on the todo list or could we use custom transformations to achieve that?

**Comment by dcodeIO** [comment] 2018-06-27 22:05
> One thing which would make life super convenient is having access to wasm's namespaces when importing external functions. Do you have that on the todo list or could we use custom transformations to achieve that?

I actually just implemented this as a decorator, but didn't commit it yet. New behavior will be to use the file name without extension as the new default module name for `declare`d functions (instead of `env`), plus a new decorator `@external` that either takes one string argument to change the external name of the element only or two string arguments to change the external names of both the module and element. So, for example:

```ts
// ethereum.ts
@external("return")
export declare function return_(): void;
```

will yield an importable file with an export `return_` that resolves to the import `ethereum.return`.

**Comment by axic** [comment] 2018-06-27 22:12
That sounds awesome, let me know when it's available.

Now we only need to learn how to create efficient types (for example for an address, value, storage keys and values - all bignums) and use them in our wrappers.

p.s. `return` should not be an issue anymore if the method is renamed to the proposed `finish`.

**Comment by MaxGraey** [comment] 2018-06-27 22:18
@axic Actully I already start working on [bignum](https://github.com/MaxGraey/bignum.wasm) which contain signed and unsigned integers for 128/256-bit. Also support `safe` (guarded) equivalent types which unreachable during overflowing. Fixed point as well. But this still in progress

**Comment by axic** [comment] 2018-06-27 22:19
@MaxGraey thanks, actually saw it today. Would you recommend using it right now? Would our experimentation with it be useful feedback for you?

**Comment by MaxGraey** [comment] 2018-06-27 22:29
Currently it's mostly untested and uncompleted. Only `u128` and `safe.u128` complete except division and reminder ops but still may contain bugs. Some part under safe namespace not compiled yet in reason on this [issue](https://github.com/AssemblyScript/assemblyscript/issues/127).

Currently I finished `itoa` which required `AnyInt#toString()` and could focused on *bignum* I hope)

**Comment by dcodeIO** [comment] 2018-06-27 23:46
@axic `@external` just landed ([test case](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/external.ts)).

**Comment by dcodeIO** [comment] 2018-06-28 00:37
[Here's a little fork](https://github.com/dcodeIO/wrc20-challenge) of @lrettig's demo with the new features and a simple extension to the standard library integrated. Hope it helps :)

**Comment by lrettig** [comment] 2018-06-28 01:00
Amazing. I love that the seven steps are now four. Thanks :) can't wait to spend more time digging into this and building an ethereum toolchain around it.

Sent via Superhuman iOS ( https://sprh.mn/?vip=lane@ethereum.org )

**Comment by axic** [comment] 2018-09-06 14:16
Thank you @dcodeIO and @MaxGraey again for the help. I am closing this issue now as pretty much everything was sorted 🎉

**Closed by axic** 2018-09-06 14:16 UTC
