### ISSUE TITLE
CREATE doesn't work

### ISSUE THREAD

**Issue by jwasinger** [ewasm/hera#122] opened 2018-01-24 16:23 UTC
See this branch with the test case in order to reproduce: https://github.com/ewasm/tests/tree/create-test

This is all the output I get:

```
Executing...
useGas 300
create0 14 0 132
```

**Comment by axic** [comment] 2018-01-25 01:12
What is the return value of `create` (it is `i32`)?

**Comment by jakelang** [comment] 2018-01-29 21:46
@jwasinger please try out the create-fix branch.

**Comment by jwasinger** [comment] 2018-01-31 17:45
Updated the test case.  I am getting back a code of `0x02`: revert.

**Comment by jakelang** [comment] 2018-02-01 02:23
Well, at least we know that works :smile: 
Looking into the cause of the problem, now that we know it is failing correctly.

**Comment by axic** [comment] 2018-03-14 14:24
I think this has been fixed with https://github.com/ethereum/cpp-ethereum/pull/4888

**Comment by axic** [comment] 2018-03-22 01:57
ping @jwasinger

**Comment by axic** [comment] 2018-03-22 02:16
Probably this is the same underlying problem as #129.

**Closed** 2018-03-22 21:24 UTC
Labels: bug, in progress
