### ISSUE TITLE
Hera/evmc/cpp chokes on wasm codes with invalid namespace

### ISSUE THREAD

**Issue by cdetrio** [ewasm/hera#259] opened 2018-06-27 03:35 UTC
It prints the following error messages and then a subsequent block never comes.

```
2018-06-26 19:17:45 eth client 1 blocks imported in 0 ms (2036.66 blocks/s) in #20
2018-06-26 19:18:01 eth client 1 blocks imported in 0 ms (1865.67 blocks/s) in #21
2018-06-26 19:18:03 eth client 1 blocks imported in 0 ms (1574.8 blocks/s) in #22
2018-06-26 19:18:11 eth client 1 blocks imported in 0 ms (2004.01 blocks/s) in #23
2018-06-26 19:18:28 eth client 1 blocks imported in 0 ms (2087.68 blocks/s) in #24
Executing...
Import from invalid namespace.
2018-06-26 19:18:50 aleth warn Internal VM Error (13)
/home/builder/project/libevm/EVMC.cpp(77): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256&, dev::eth::ExtVMFace&, const OnOpFunc&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = 13

2018-06-26 19:19:01 eth client 1 blocks imported in 0 ms (1855.29 blocks/s) in #25
2018-06-26 19:19:06 eth client 1 blocks imported in 0 ms (1420.45 blocks/s) in #26
2018-06-26 19:19:09 eth client 1 blocks imported in 0 ms (2212.39 blocks/s) in #27
Executing...
Import from invalid namespace.
2018-06-26 19:19:11 eth warn Internal VM Error (13)
/home/builder/project/libevm/EVMC.cpp(77): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256&, dev::eth::ExtVMFace&, const OnOpFunc&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = 13

2018-06-26 19:19:12 eth warn 


    Import Failure     /home/builder/project/libethereum/Block.cpp(644): Throw in function dev::u256 dev::eth::Block::enact(const dev::eth::VerifiedBlockRef&, const dev::eth::BlockChain&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InvalidStateRoot>
[dev::tag_get_h256*] = 619ce5ffdacf048784b248a59e726562aa47e8d2489ead926e3180ba5fd29bb3
[dev::tag_extraData*] = [ type: std::vector<unsigned char, std::allocator<unsigned char> >, size: 24, dump: d0 73 05 10 70 7f 00 00 e7 73 05 10 70 7f 00 00 ]
[dev::tag_required_h256*] = 46f09189599356449753fb985b2b0751b2c36fe0d1125726f37e2389c7aefbae
[dev::eth::tag_now*] = 1530040752
[dev::eth::tag_block*] = [ type: std::vector<unsigned char, std::allocator<unsigned char> >, size: 24, dump: a0 74 05 10 70 7f 00 00 b6 76 05 10 70 7f 00 00 ]


                       Bad Block #00000028.9d040f9e…                      


2018-06-26 19:19:12 eth client Tried to seal sealed block...
2018-06-26 19:19:13 eth client Tried to seal sealed block...
2018-06-26 19:19:14 eth client Tried to seal sealed block...
2018-06-26 19:19:15 eth client Tried to seal sealed block...
2018-06-26 19:19:16 eth client Tried to seal sealed block...
2018-06-26 19:19:17 eth client Tried to seal sealed block...
2018-06-26 19:19:18 eth client Tried to seal sealed block...
2018-06-26 19:19:19 eth client Tried to seal sealed block...
2018-06-26 19:19:20 eth client Tried to seal sealed block...
2018-06-26 19:19:21 eth client Tried to seal sealed block...
2018-06-26 19:19:22 eth client Tried to seal sealed block...
2018-06-26 19:19:23 eth client Tried to seal sealed block...
2018-06-26 19:19:24 eth client Tried to seal sealed block...
2018-06-26 19:19:25 eth client Tried to seal sealed block...
2018-06-26 19:19:26 eth client Tried to seal sealed block...
2018-06-26 19:19:27 eth client Tried to seal sealed block...
2018-06-26 19:19:28 eth client Tried to seal sealed block...
2018-06-26 19:19:29 eth client Tried to seal sealed block...
2018-06-26 19:19:30 eth client Tried to seal sealed block...
2018-06-26 19:19:31 eth client Tried to seal sealed block...
2018-06-26 19:19:32 eth client Tried to seal sealed block...
```

**Comment by axic** [comment] 2018-06-27 09:15
```
Import from invalid namespace.
2018-06-26 19:18:50 aleth warn Internal VM Error (13)
/home/builder/project/libevm/EVMC.cpp(77): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256&, dev::eth::ExtVMFace&, const OnOpFunc&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = 13
```

To decompose:
1) the "Import from invalid namespace." is an internal error, because it should rejected by the sentinel contract at deploy time, but since we do not have that yet, we require the user to do it
2) the `EVMC_INTERNAL_ERROR` is considered a panic in EVMC, aleth should deal with tit properly

Issue 2) seems to be a bug, @chfast @gumb0 can you check?

**Comment by chfast** [comment] 2018-06-27 09:22
I don't believe there a way to handle the `EVMC_INTERNAL_ERROR` in incoming blocks. you might want to drop the block if you was mining it, but that's very complicated in our current architecture of the client where the import part does not recognize where the block comes from. 

@gumb0 should be able to say much more about it. It looks the block was marked as a bad block. Why is the client not progressing?

**Comment by gumb0** [comment] 2018-06-27 09:49
The block being mined is updated in only when the blockchain is updated, so it does not progress as it thinks there's no need to, chain head didn't change.

I guess we can try to work around it, as `Client` which manages the mining receives a callback when invalid block was processed.
https://github.com/ethereum/cpp-ethereum/blob/9fe8dc53d22b8aa637f86d7c045002300e8b99ee/libethereum/Client.cpp#L173-L185
We could check here if it's the same block we were mining and `restartMining()` if yes

**Comment by gumb0** [comment] 2018-06-27 09:50
I can try it if you describe how to reproduce it.

**Comment by axic** [comment] 2018-06-27 11:20
@gumb0 Probably the simplest is if you change `evmc` in aleth to always return an `EVMC_INTERNAL_ERROR` response code and run it with `aleth-interpreter`. That should trigger the problem.

**Comment by lrettig** [comment] 2018-06-27 11:53
Re: issue no. 2 above, this looks very similar to the error I encountered in https://github.com/ewasm/tests/pull/52 which has me stumped. I feel like this just started, maybe there is an underlying hera/cpp issue here -- why aren't these exceptions being trapped? Apologies if I'm misunderstanding something.

**Comment by gumb0** [comment] 2018-06-27 12:20
@axic Thanks, I'll try it

@lrettig Doesn't look similar to me, there's another evmc statsus code in your issue
```
[dev::eth::tag_evmcStatusCode*] = 9
```

**Comment by gumb0** [comment] 2018-06-28 10:41
After messing with code I think the problem is different. The transaction that caused exception is considered invalid and is not added to the mined block - this is correct.
But looks like we don't handle internal VM exception properly - the state changes are not rolled backed after it and as a result the state root hash is incorrect when we construct the block.

**Comment by gumb0** [comment] 2018-06-28 10:50
@cdetrio Could you try it with this fix https://github.com/ethereum/cpp-ethereum/pull/5101 ?

**Comment by chfast** [comment] 2018-07-17 08:40
Fixed.

**Closed by chfast** 2018-07-17 08:40 UTC
